version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  lint:
    executor: python/default
    steps:
      - checkout
      - run:
          name: "Run pylint"
          command: |
            pylint app.py
workflows:
  lint-test-deploy:
    jobs: 
      - lint
