version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  lint:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: "Run pylint"
          command: |
            . venv/bin/activate
            pylint app.py
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
  test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: "Run tests"
          command: |
            pip install -r requirements.txt
            python3 test.py
workflows:
  lint-test-deploy:
    jobs: 
      - lint
      - test
